/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoorsRouteImport } from './routes/doors'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as WorkRouteImport } from './routes/work'
import { Route as DoorsIndexRouteImport } from './routes/doors.index'
import { Route as DoorsSlugRouteImport } from './routes/doors.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsRoute = DoorsRouteImport.update({
  id: '/doors',
  path: '/doors',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsIndexRoute = DoorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoorsRoute,
} as any)
const DoorsSlugRoute = DoorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/doors': typeof DoorsRouteWithChildren
  '/installation': typeof InstallationRoute
  '/privacy': typeof PrivacyRoute
  '/repair': typeof RepairRoute
  '/work': typeof WorkRoute
  '/doors/$slug': typeof DoorsSlugRoute
  '/doors/': typeof DoorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/installation': typeof InstallationRoute
  '/privacy': typeof PrivacyRoute
  '/repair': typeof RepairRoute
  '/work': typeof WorkRoute
  '/doors/$slug': typeof DoorsSlugRoute
  '/doors': typeof DoorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/doors': typeof DoorsRouteWithChildren
  '/installation': typeof InstallationRoute
  '/privacy': typeof PrivacyRoute
  '/repair': typeof RepairRoute
  '/work': typeof WorkRoute
  '/doors/$slug': typeof DoorsSlugRoute
  '/doors/': typeof DoorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/doors'
    | '/installation'
    | '/privacy'
    | '/repair'
    | '/work'
    | '/doors/$slug'
    | '/doors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/installation'
    | '/privacy'
    | '/repair'
    | '/work'
    | '/doors/$slug'
    | '/doors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/doors'
    | '/installation'
    | '/privacy'
    | '/repair'
    | '/work'
    | '/doors/$slug'
    | '/doors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  DoorsRoute: typeof DoorsRouteWithChildren
  InstallationRoute: typeof InstallationRoute
  PrivacyRoute: typeof PrivacyRoute
  RepairRoute: typeof RepairRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors': {
      id: '/doors'
      path: '/doors'
      fullPath: '/doors'
      preLoaderRoute: typeof DoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors/': {
      id: '/doors/'
      path: '/'
      fullPath: '/doors/'
      preLoaderRoute: typeof DoorsIndexRouteImport
      parentRoute: typeof DoorsRoute
    }
    '/doors/$slug': {
      id: '/doors/$slug'
      path: '/$slug'
      fullPath: '/doors/$slug'
      preLoaderRoute: typeof DoorsSlugRouteImport
      parentRoute: typeof DoorsRoute
    }
  }
}

interface DoorsRouteChildren {
  DoorsSlugRoute: typeof DoorsSlugRoute
  DoorsIndexRoute: typeof DoorsIndexRoute
}

const DoorsRouteChildren: DoorsRouteChildren = {
  DoorsSlugRoute: DoorsSlugRoute,
  DoorsIndexRoute: DoorsIndexRoute,
}

const DoorsRouteWithChildren = DoorsRoute._addFileChildren(DoorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  DoorsRoute: DoorsRouteWithChildren,
  InstallationRoute: InstallationRoute,
  PrivacyRoute: PrivacyRoute,
  RepairRoute: RepairRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
